apiVersion: kips.faux.ninja/v1alpha1
kind: ServiceBridge
metadata:
  name: servicebridge-sample-api
spec:
  targetService: # This is the service that we're redirecting and routing to the remote (dev) machine
    name: api
    relayName: relay1
    ports:
    - name: api
      remotePort:  9000
  additionalServices: []