apiVersion: kips.faux.ninja/v1alpha1
kind: ServiceBridge
metadata:
  name: servicebridge-sample-web
spec:
  targetService: # This is the service that we're redirecting and routing to the remote (dev) machine
    name: web
    relayName: relay1
    ports:
    - name: http
      remotePort: 9001
  additionalServices: # These are services that we want the remote machine to be able to forward to
    - name: api
      relayName: relay2
      ports:
        - name: api
          remotePort: 9100
  