apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: servicebridges.kips.faux.ninja
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    name: State
    type: string
  group: kips.faux.ninja
  names:
    kind: ServiceBridge
    plural: servicebridges
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ServiceBridge is the Schema for the servicebridges API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ServiceBridgeSpec defines the desired state of ServiceBridge
          properties:
            additionalServices:
              description: AdditionalServices are the services to redirect from the
                remote connection
              items:
                description: AdditionalService holds the configuration for services
                  that we want the remote machine to be able to forward to
                properties:
                  name:
                    description: Name of the service to redirect from the remote connection
                    type: string
                  ports:
                    description: Ports is a collection of ports to redirect
                    items:
                      description: AdditionalServicePort holds the configuration for
                        a port on an AdditionalService
                      properties:
                        name:
                          description: Name is the name of the service to redirect
                            from the remote connection
                          type: string
                        remotePort:
                          description: RemotePort is the port to use on the remote
                            machine to route traffic to this service
                          type: integer
                      required:
                      - name
                      - remotePort
                      type: object
                    type: array
                  relayName:
                    description: RelayName is the name of the Azure Relay to connect
                      via
                    type: string
                required:
                - name
                - ports
                - relayName
                type: object
              type: array
            targetService:
              description: TargetService is the service to redirect to the remote
                connection
              properties:
                name:
                  description: Name is the name of the service to redirect to the
                    remote connection
                  type: string
                ports:
                  description: Ports is a collection of ports to redirect
                  items:
                    description: TargetServicePort holds the configuration for a targeted
                      port on a service
                    properties:
                      name:
                        description: Name of the targeted port
                        type: string
                      remotePort:
                        description: RemotePort is the remote port to forward to
                        type: integer
                    required:
                    - name
                    - remotePort
                    type: object
                  type: array
                relayName:
                  description: RelayName is the name of the Azure Relay to connect
                    via
                  type: string
              required:
              - name
              - ports
              - relayName
              type: object
          required:
          - additionalServices
          - targetService
          type: object
        status:
          description: ServiceBridgeStatus defines the observed state of ServiceBridge
          properties:
            clientAzbridgeConfig:
              description: ClientAzbridgeConfig contains the Azbridge config to use
                on the remote connection
              type: string
            errorState:
              description: ErrorState is used to control error back-offs
              properties:
                lastBackOffPeriodInSeconds:
                  type: integer
                stage:
                  type: string
              required:
              - lastBackOffPeriodInSeconds
              - stage
              type: object
            state:
              description: State gives a high level indication of the ServiceBridge
                state
              type: string
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
