apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: kips-operator-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: servicebridges.kips.faux.ninja
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    name: State
    type: string
  group: kips.faux.ninja
  names:
    kind: ServiceBridge
    plural: servicebridges
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ServiceBridge is the Schema for the servicebridges API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ServiceBridgeSpec defines the desired state of ServiceBridge
          properties:
            additionalServices:
              items:
                description: AdditionalService holds the configuration for services
                  that we want the remote machine to be able to forward to
                properties:
                  name:
                    type: string
                  ports:
                    items:
                      description: AdditionalServicePort holds the configuration for
                        a port on an AdditionalService
                      properties:
                        name:
                          type: string
                        remotePort:
                          type: integer
                      required:
                      - name
                      - remotePort
                      type: object
                    type: array
                required:
                - name
                - ports
                type: object
              type: array
            targetService:
              description: TargetService represents a service targeted by the ServiceBridge
              properties:
                name:
                  type: string
                ports:
                  items:
                    description: TargetServicePort holds the configuration for a targeted
                      port on a service
                    properties:
                      name:
                        type: string
                      remotePort:
                        type: integer
                    required:
                    - name
                    - remotePort
                    type: object
                  type: array
              required:
              - name
              - ports
              type: object
          required:
          - additionalServices
          - targetService
          type: object
        status:
          description: ServiceBridgeStatus defines the observed state of ServiceBridge
          properties:
            clientAzbridgeConfig:
              type: string
            message:
              type: string
            state:
              description: ServiceBridgeState represents the state of the ServiceBridge
              type: string
            temp:
              type: string
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kips-operator-leader-election-role
  namespace: kips-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kips-operator-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kips.faux.ninja
  resources:
  - servicebridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kips.faux.ninja
  resources:
  - servicebridges/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kips-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kips-operator-leader-election-rolebinding
  namespace: kips-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kips-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kips-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kips-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kips-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kips-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kips-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kips-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kips-operator-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: kips-operator-controller-manager-metrics-service
  namespace: kips-operator-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: kips-operator-controller-manager
  namespace: kips-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: stuartleeks/kips-operator:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
