apiVersion: kips.faux.ninja/v1alpha1
kind: ServiceBridge
metadata:
  name: servicebridge-sample
spec:
  targetService: # This is the service that we're redirecting and routing to the remote (dev) machine
    name: web
    ports:
    - name: http
      remotePort: 5000
  additionalServices: # These are services that we want the remote machine to be able to forward to
    - name: api
      ports:
        - name: api
          remotePort: 8081
  