apiVersion: kips.faux.ninja/v1alpha1
kind: ServiceBridge
metadata:
  name: servicebridge-sample-api
spec:
  targetService: # This is the service that we're redirecting and routing to the remote (dev) machine
    name: api
    ports:
    - name: api
      remotePort: 5000
  