// +build !ignore_autogenerated

// autogenerated by controller-gen object, do not modify manually

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalService) DeepCopyInto(out *AdditionalService) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]AdditionalServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalService.
func (in *AdditionalService) DeepCopy() *AdditionalService {
	if in == nil {
		return nil
	}
	out := new(AdditionalService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalServicePort) DeepCopyInto(out *AdditionalServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalServicePort.
func (in *AdditionalServicePort) DeepCopy() *AdditionalServicePort {
	if in == nil {
		return nil
	}
	out := new(AdditionalServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBridge) DeepCopyInto(out *ServiceBridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBridge.
func (in *ServiceBridge) DeepCopy() *ServiceBridge {
	if in == nil {
		return nil
	}
	out := new(ServiceBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceBridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBridgeList) DeepCopyInto(out *ServiceBridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceBridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBridgeList.
func (in *ServiceBridgeList) DeepCopy() *ServiceBridgeList {
	if in == nil {
		return nil
	}
	out := new(ServiceBridgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceBridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBridgeSpec) DeepCopyInto(out *ServiceBridgeSpec) {
	*out = *in
	in.TargetService.DeepCopyInto(&out.TargetService)
	if in.AdditionalServices != nil {
		in, out := &in.AdditionalServices, &out.AdditionalServices
		*out = make([]AdditionalService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBridgeSpec.
func (in *ServiceBridgeSpec) DeepCopy() *ServiceBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBridgeStatus) DeepCopyInto(out *ServiceBridgeStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(ServiceBridgeState)
		**out = **in
	}
	if in.ClientAzbridgeConfig != nil {
		in, out := &in.ClientAzbridgeConfig, &out.ClientAzbridgeConfig
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBridgeStatus.
func (in *ServiceBridgeStatus) DeepCopy() *ServiceBridgeStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceBridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetService) DeepCopyInto(out *TargetService) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]TargetServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetService.
func (in *TargetService) DeepCopy() *TargetService {
	if in == nil {
		return nil
	}
	out := new(TargetService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetServicePort) DeepCopyInto(out *TargetServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetServicePort.
func (in *TargetServicePort) DeepCopy() *TargetServicePort {
	if in == nil {
		return nil
	}
	out := new(TargetServicePort)
	in.DeepCopyInto(out)
	return out
}
