
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: servicebridges.kips.faux.ninja
spec:
  group: kips.faux.ninja
  names:
    kind: ServiceBridge
    plural: servicebridges
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ServiceBridge is the Schema for the servicebridges API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ServiceBridgeSpec defines the desired state of ServiceBridge
          properties:
            additionalServices:
              items:
                description: AdditionalService holds the configuration for services
                  that we want the remote machine to be able to forward to
                properties:
                  name:
                    type: string
                  ports:
                    items:
                      description: AdditionalServicePort holds the configuration for
                        a port on an AdditionalService
                      properties:
                        name:
                          type: string
                        remotePort:
                          type: integer
                      required:
                      - name
                      - remotePort
                      type: object
                    type: array
                required:
                - name
                - ports
                type: object
              type: array
            targetService:
              description: TargetService represents a service targetted by the ServiceBridge
              properties:
                name:
                  type: string
                ports:
                  items:
                    description: TargetServicePort holds the configuration for a targetted
                      port on a service
                    properties:
                      name:
                        type: string
                      remotePort:
                        type: integer
                    required:
                    - name
                    - remotePort
                    type: object
                  type: array
              required:
              - name
              - ports
              type: object
          required:
          - additionalServices
          - targetService
          type: object
        status:
          description: ServiceBridgeStatus defines the observed state of ServiceBridge
          properties:
            clientAzbridgeConfig:
              type: string
            message:
              type: string
            temp:
              type: string
          required:
          - clientAzbridgeConfig
          - message
          - temp
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
